services:
  micro-service-first:
    image: jaypatell15/validator-microservice
    environment:
      NODE_ENV: production
    ports:
      - 6000:6000
    volumes:
      - .:/app/files
    networks:
      - microservice-first-second
    depends_on:
      - micro-service-second
    
  micro-service-second:
    image: jaypatell15/calculate-microservice
    environment:
      NODE_ENV: production
    ports:
      - 6060:6060
    volumes:
      - .:/app/files
    networks:
      - microservice-first-second

volumes:
  microservice-volumes:
    external: false

networks:
  microservice-first-second:
